### ISSUE TITLE
Make error: bin/pico2wave.c:22:10: fatal error: popt.h: No such file or directory

### ISSUE THREAD

**Issue by stellarore** [naggety/picotts#8]
I'm trying to install picotts on Raspberry pi 2B+, Raspian Buster.
I followed the readme.md up to ./configure.  Then when I run make, I get the output:

`~/picotts/pico $ sudo make
gcc -DPACKAGE_NAME=\"svox\" -DPACKAGE_TARNAME=\"svox\" -DPACKAGE_VERSION=\"1.0\"  -DPACKAGE_STRING=\"svox\ 1.0\" -DPACKAGE_BUGREPORT=\"math.parent@gmail.com\" -D PACKAGE_URL=\"\" -DPACKAGE=\"svox\" -DVERSION=\"1.0\" -DSTDC_HEADERS=1 -DHAVE_SY S_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMOR Y_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1  -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -I.    -Wall -Dpicolangdir=\"/usr/local /share/pico/lang\" -I lib -g -O2 -MT pico2wave-pico2wave.o -MD -MP -MF .deps/pic o2wave-pico2wave.Tpo -c -o pico2wave-pico2wave.o `test -f 'bin/pico2wave.c' \|\| e cho './bin/pico2wave.c 
bin/pico2wave.c:22:10: fatal error: popt.h: No such file or directory
#include   <popt.h>  ^~~~~~~~
 compilation terminated. 
make: *** [Makefile:865: pico2wave-pico2wave.o] Error 1
`

If I try `$ apt install popt `, it says:
`
Package popt is not available, but is referred to by another package
 This may mean that the package is missing, has been obsoleted, or
  is only available from another source
 However the following packages replace it:
  libpopt0     libpopt-dev`

I do have libpopt0 installed already.

**Comment by jpwhiting** [comment]
Looks like you need the package that includes the header files. From looking at packages.debian.org it's probably called libpopt-dev https://packages.debian.org/search?searchon=contents&keywords=popt.h&mode=path&suite=stable&arch=any install that one and you'll have the popt.h header that you're missing.

**Comment by nahoj** [comment]
~~This worked on Ubuntu 21.10~~, thanks @jpwhiting.

Actually picotts is packaged for Ubuntu; the package name is `libttspico-utils`.

**Comment by jpwhiting** [comment]
no problem

**Comment by BlurryRoots** [comment]
On MacOS you may want to install popt via homebrew: `brew install popt`

**Comment by oscar-lima** [comment]
On ubuntu 20.04 ```sudo apt install libpopt-dev``` worked for me. Should this be added to the README?

**Comment by pragnakalpdev30** [comment]
@oscar-lima yes it's works for me as well.
